- name: create folder /opt/nginx
  ansible.builtin.file:
    path: /opt/nginx
    owner: 1000
    group: 1000
    state: directory
    mode: '0755'

- name: copy nginx config file
  copy: src=/Users/nikita_dir/Documents/projects/NikitaAnsible/roles/jenkins/files/vhost.conf dest=/opt/nginx/vhost.conf

- name: pull nginx image
  docker_image:
    name: nginx:stable
    source: pull

- name: deploy nginx docker container
  docker_container:
    name: "nginx"
    image: "nginx:stable"
    detach: yes
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: "proxy"

    volumes:
      - /opt/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - /etc/letsencrypt/live/jenkins.nikitasdomain.tk/fullchain.pem:/etc/letsencrypt/live/jenkins.nikitasdomain.tk/jenkins.nikitasdomain.tk.crt
      - /etc/letsencrypt/live/jenkins.nikitasdomain.tk/privkey.pem:/etc/letsencrypt/live/jenkins.nikitasdomain.tk/jenkins.nikitasdomain.tk.key